#!/bin/bash

set -e

metadata_file=$(pwd)/test/data/metadata.json

echo "Using metadata file $metadata_file"

./rebar compile

env EC2_METADATA_FILE=$metadata_file ERL_AFLAGS="-s ec2_metadata_mock" ./deps/etest/bin/etest-runner
